apiVersion: v1
kind: Secret
metadata:
  name: fastapi-env-secrets
type: Opaque
stringData:
  POSTGRES_USER: musma
  POSTGRES_PASSWORD: musma0812!
  POSTGRES_SERVER: 172.30.1.112
  POSTGRES_PORT: "32432"
  POSTGRES_DB: rabbit_test
  RABBITMQ_URL: amqp://musma:musma0812@172.30.1.114:4788/
  RABBITMQ_QUEUE: message_queue
  RABBITMQ_VIRTUAL_HOST: /
  RABBITMQ_EXCHANGE: musma
  RABBITMQ_ROUTING_KEY: sensor.*.device.*
  PROJECT_NAME: FastAPIProject
  MONGODB_URL: mongodb://admin:musma0812%40!@172.30.1.113:31639/database?authSource=admin
  MONGODB_DATABASE: message-test
  CORS_ORIGINS: "*"
  CORS_ALLOW_CREDENTIALS: "True"
  CORS_ALLOW_METHODS: "*"
  CORS_ALLOW_HEADERS: "*"
